name: android device tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./flutter/example/android
    strategy:
      matrix:
        api-level: [21]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: kill adb
        run: |
          adb kill-server
          adb start-server

      - name: setup gradle wrapper
        run: gradle wrapper

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedCheck
